CREATE TABLE clientes
(
    cliente_id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre              VARCHAR(100)                             NOT NULL,
    documento_identidad VARCHAR(20)                              NOT NULL,
    tipo_documento      VARCHAR(20)                              NOT NULL,
    nacionalidad        VARCHAR(50)                              NOT NULL,
    telefono            VARCHAR(20)                              NOT NULL,
    email               VARCHAR(100)                             NOT NULL,
    fecha_registro      TIMESTAMP WITHOUT TIME ZONE,
    activo              BOOLEAN,
    preferencias        VARCHAR(255),
    alergias            VARCHAR(255),
    password_hash       VARCHAR(255),
    CONSTRAINT pk_clientes PRIMARY KEY (cliente_id)
);